### ISSUE TITLE
Error being thrown Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by XCHSystems** [lmacken/plow#1]
```
/farming/./plow.py:201: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
🌱 Plow running...
🧑‍🌾  plowing to /Plotdisks/Disk08
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-19-20-5d853f7a3a9a570157f57d44a93e9c4edc82cbce5933809c5e5a9586249dbd2e.plot ➡️  /Plotdisks/Disk08
🧑‍🌾  plowing to /Plotdisks/Disk14
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-19-26-0a8863e4a1ac1b5aefcecd8d9a51dd1d40fe1f0112f3d550d851a05ab38f8a9e.plot ➡️  /Plotdisks/Disk14
🧑‍🌾  plowing to /Plotdisks/Disk04
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-19-51-cd83a789eb5338d249f8ba33d5f4193312477897d2148f8dc88c514bd0bb2fb2.plot ➡️  /Plotdisks/Disk04
🧑‍🌾  plowing to /Plotdisks/Disk02
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-20-00-c143611b20c8ed74dd7791cb8fd5757770214f8e1fec07c637f92f5018dec098.plot ➡️  /Plotdisks/Disk02
🧑‍🌾  plowing to /Plotdisks/Disk07
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-20-09-db6f4fa23e3ae7cc3f5d6a9046ed394ee0ae9146bdaee117ea7ceca0feac17ee.plot ➡️  /Plotdisks/Disk07
🧑‍🌾  plowing to /Plotdisks/Disk10
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-20-16-2ea7cd129277f37a785141befe5b659566bc8e1d114952ae70abe8c99bd56388.plot ➡️  /Plotdisks/Disk10
🧑‍🌾  plowing to /Plotdisks/Disk11
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-20-24-12813baf6ef57a01ece15dd03788d25a4fba765c8042c330ec432d7fc1a443d1.plot ➡️  /Plotdisks/Disk11
🧑‍🌾  plowing to /Plotdisks/Disk05
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-20-49-6f503fd8eb96269a081f84189cf4f04e6b8c431782e8375904995b578f9d2cfc.plot ➡️  /Plotdisks/Disk05
🧑‍🌾  plowing to /Plotdisks/Disk15
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-19-11-f167cd49a5653b7d94a07400e3dfd42d11ba48c370c99a88839d7f6fd8bf6017.plot ➡️  /Plotdisks/Disk15
🧑‍🌾  plowing to /Plotdisks/Disk12
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-19-02-6142f2d69d7e76860cf3b581f489c1059dccc9750265732bed72f36d1a1faa77.plot ➡️  /Plotdisks/Disk12
🧑‍🌾  plowing to /Plotdisks/Disk09
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-19-13-d3c9bd100092804a52fe880a70607b80dbaad9b3e53dc2f41c3229d76457a1a3.plot ➡️  /Plotdisks/Disk09
🧑‍🌾  plowing to /Plotdisks/Disk01
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-19-04-9d772523470309a2488219921c4ba46a14efed3bf229065ed627cecbd97f628c.plot ➡️  /Plotdisks/Disk01
🧑‍🌾  plowing to /Plotdisks/Disk13
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-19-35-7c513fd65ca8d19d9562c5d505a13231f3360cd6da00eaace93ebb20d73a409f.plot ➡️  /Plotdisks/Disk13
🧑‍🌾  plowing to /Plotdisks/Disk03
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-19-44-1b8b48ac18c2023a98c1d1f8c528c5625431f47d3d446d329bdd49ce4ae78468.plot ➡️  /Plotdisks/Disk03
🧑‍🌾  plowing to /Plotdisks/Disk06
🚜 /Plotdisks/RAID/Disk01/plot-k32-2023-02-10-19-06-8577fb85636d757af65a03465907277dd4294010351db8981937900ca04bc4d4.plot ➡️  /Plotdisks/Disk06
Traceback (most recent call last):
  File "/farming/./plow.py", line 203, in <module>
    loop.run_until_complete(main(SOURCES, loop))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/farming/./plow.py", line 197, in main
    await asyncio.gather(*futures)
  File "/farming/./plow.py", line 72, in plotfinder
    await plotwatcher(paths, plot_queue, loop)
  File "/farming/./plow.py", line 76, in plotwatcher
    watcher = aionotify.Watcher()
AttributeError: module 'aionotify' has no attribute 'Watcher'

```

**Comment by lmacken** [comment]
That's odd... `aionotify.Watcher` is in the top level namespace: https://github.com/rbarrois/aionotify/blob/master/aionotify/__init__.py#L7

Can you try running this command to make sure you have the latest version of `aionotify`? Thanks
```bash
$ python -c 'import aionotify; print(aionotify.__version__)'
0.2.0
```

**Comment by XCHSystems** [comment]
I managed to sort it, it was a problem between the keyboard and the chair.

Incidentally I was doing the following

./plow.py

Instead of

python3 ./plow.py

**Comment by lmacken** [comment]
Interesting, `./plow.py` works for me. We use `#!/usr/bin/env python3` in the header. I'm guessing `env python3` returns the system python for you and not the virtualenv, or some different version?
