### ISSUE TITLE
Clear Linux error

### ISSUE THREAD

**Issue by hajes** [lmacken/plow#9]
./plow.py 
Traceback (most recent call last):
  File "/home/hajes/./plow.py", line 16, in <module>
    import aionotify
  File "/home/hajes/.local/lib/python3.11/site-packages/aionotify/__init__.py", line 5, in <module>
    from .base import Watcher
  File "/home/hajes/.local/lib/python3.11/site-packages/aionotify/base.py", line 10, in <module>
    from . import aioutils
  File "/home/hajes/.local/lib/python3.11/site-packages/aionotify/aioutils.py", line 122, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

**Comment by hajes** [comment]
python3 -m pip install aioutils
Defaulting to user installation because normal site-packages is not writeable
DEPRECATION: Loading egg at /usr/lib/python3.11/site-packages/cupshelpers-1.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Collecting aioutils
  Using cached aioutils-0.3.10.tar.gz (9.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4b8_y1xv/aioutils_c347824d546a4c9f962684db1a9ecb9c/setup.py", line 5, in <module>
          from aioutils import __version__
        File "/tmp/pip-install-4b8_y1xv/aioutils_c347824d546a4c9f962684db1a9ecb9c/aioutils/__init__.py", line 1, in <module>
          from .pool import Pool, Group
        File "/tmp/pip-install-4b8_y1xv/aioutils_c347824d546a4c9f962684db1a9ecb9c/aioutils/pool.py", line 46
          task = asyncio.async(coro_or_future)
                         ^^^^^
      SyntaxError: invalid syntax
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by hajes** [comment]
looks like python 3.11 refuses to work with outdated `aioutils`

**Comment by hajes** [comment]
https://stackoverflow.com/questions/74345065/attributeerror-module-asyncio-has-no-attribute-coroutine-in-python-3-11

still comes with errors

**Comment by SpikeTM** [comment]
Same issue python 3.11. Any resolution?

**Comment by hajes** [comment]
It uses outdated modules...i have written own script

**Comment by SpikeTM** [comment]
Very nice,.. mind sharing your script?

**Comment by lmacken** [comment]
Thanks for the report. Yeah it looks like `aionotify` upstream stopped doing releases, so it's currently broken on `python3.11+`. https://github.com/rbarrois/aionotify/pull/19/commits

**Comment by lmacken** [comment]
We could potentially port to another library like https://github.com/absperf/asyncinotify/

**Comment by hajes** [comment]
So far, my kludge is a custom bash script. Of course, it is a dumb script that needs some manual handling - otherwise it will try to copy all at once to all destinations.

Eventually, every major distro will move to 3.11+. It looks like this module is not developed anymore.

**Comment by lmacken** [comment]
I updated the README to mention this, https://github.com/lmacken/plow#known-issues
